[package]
name = "tuxread-core"
description = "Read-only engine for Linux filesystems (TuxRead)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gptman.workspace = true
mbrman.workspace = true
ext4-view.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
base64.workspace = true
